project_root: ${hydra:runtime.cwd}

data_dir: ${oc.env:TWINCART_DATA_DIR,${paths.project_root}/data}
models_dir: ${oc.env:TWINCART_MODELS_DIR,${paths.project_root}/models}
plots_dir: ${paths.project_root}/plots

hydra_out_dir: ${paths.project_root}/outputs

artifacts_dir: ${paths.data_dir}/artifacts
embeddings_dir: ${paths.artifacts_dir}/embeddings
indices_dir: ${paths.artifacts_dir}/indices
submissions_dir: ${paths.artifacts_dir}/submissions
