defaults:
  - paths@paths: default
  - data@data: shopee
  - transforms@transforms: shopee
  - _self_

task: export

export:
  fold: 0

  image_ckpt: ${paths.models_dir}/checkpoints/image/fold_${export.fold}/best.ckpt
  text_ckpt: ${paths.models_dir}/checkpoints/text/fold_${export.fold}/best.ckpt

  out_dir: ${paths.models_dir}/onnx

  image_h: ${transforms.image.input_size}
  image_w: ${transforms.image.input_size}
  text_max_len: ${transforms.text.max_length}

  opset: 17
  dynamo: false

hydra:
  run:
    dir: ${paths.hydra_out_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${task}
