defaults:
  - paths@paths: default
  - model@image_model: image_nfnet_f0_gem
  - model@text_model: text_distilbert_id
  - _self_

export:
  opset: 17
  image:
    input_h: 420
    input_w: 420
    output_dir: ${paths.models_dir}/onnx/image
  text:
    max_len: 64
    output_dir: ${paths.models_dir}/onnx/text
